# Model configuration
model_name: 'distilgpt2'
dataset_name: 'ag_news'
text_column: 'text'

# Training configuration
output_dir: './results'
num_epochs: 2        # Reduced: news articles follow similar patterns
batch_size: 16       # Increased: news articles are shorter
learning_rate: 5e-5  # Increased: news data is structured
max_length: 64       # Decreased: typical news article length