# Model configuration
model_name: 'distilgpt2'  # or any other small language model from HuggingFace
dataset_name: 'ag_news'  # news articles dataset
text_column: 'text'  # column name containing the text in your dataset

# Training configuration
output_dir: './results'
num_epochs: 3
batch_size: 8
learning_rate: 0.00002  # Changed from string "2e-5" to float 0.00002
max_length: 128